id: P004636
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016761
  title: དཔལ་གསང་ཆེན་རྙིང་མ་སྒོ་ཆེན་རྒྱལ་བའི་རི་ཁྲོད་བདུད་འདུལ་གསང་སྔགས་གླིང་དགོན་གྱི་ཆོས་སྤྱོད་གཅེས་བཏུས་ཟབ་བཅུད་རིན་པོ་ཆེའི་གཏེར་མཛོད
  author: ''
  volumes:
    ce920f7b51b64ccc8e1f3af60cc16498:
      image_group_id: I01JW66
      title: ''
      volume_number: 1
      total_pages: 864
      base_file: v001.txt
