id: P004636
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016761
  title: དཔལ་གསང་ཆེན་རྙིང་མ་སྒོ་ཆེན་རྒྱལ་བའི་རི་ཁྲོད་བདུད་འདུལ་གསང་སྔགས་གླིང་དགོན་གྱི་ཆོས་སྤྱོད་གཅེས་བཏུས་ཟབ་བཅུད་རིན་པོ་ཆེའི་གཏེར་མཛོད
  author: ''
  volumes: {}
