id: I8DD34E5F
legacy_id: P004636
ocr_import_info:
  bdrc_scan_id: W00EGS1016761
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T17:45:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:13:40.114507+00:00'
last_modified: 2022-08-29 18:15:10.288567
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016761
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016761
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་གསང་ཆེན་རྙིང་མ་སྒོ་ཆེན་རྒྱལ་བའི་རི་ཁྲོད་བདུད་འདུལ་གསང་སྔགས་གླིང་དགོན་གྱི་ཆོས་སྤྱོད་གཅེས་བཏུས་ཟབ་བཅུད་རིན་པོ་ཆེའི་གཏེར་མཛོད།
statistics:
  ocr_word_mean_confidence_index: 0.8922037181547772
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I01JW66:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW66
      total_pages: 864
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW66.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8922037181547772
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
