id: I8DD34E5F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:51:10+00:00'
last_modified: '2022-06-08T02:29:08.307656+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016761
  title: དཔལ་གསང་ཆེན་རྙིང་མ་སྒོ་ཆེན་རྒྱལ་བའི་རི་ཁྲོད་བདུད་འདུལ་གསང་སྔགས་གླིང་དགོན་གྱི་ཆོས་སྤྱོད་གཅེས་བཏུས་ཟབ་བཅུད་རིན་པོ་ཆེའི་གཏེར་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1D48:
      image_group_id: I01JW66
      title: ''
      total_pages: 864
      order: 1
      base_file: 1D48.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
